Implemented epsilon-lexicase selection in selection.cljc and calculated epsilons once per generation in gp.cljc
lspector/propeller pull request #53
Opened 2022-12-29 23:24 UTC by dndang23

2022-12-30 13:57 UTC, ryanboldi requested changes
Looks good to me! I think some small organizational tweaks are needed but besides that it looks good.

Also, it would be nice to write some tests for the epsilon-generation functions when you move them to selection.

2022-12-30 13:57 UTC, ryanboldi commented on src/propeller/gp.cljc
> +
I would not define these in gp.cljc

I think add all the math stuff to src/propeller/tools/math.cljc

I would also added epsilon-list to a file in selection, and then import it.

2022-12-30 13:57 UTC, ryanboldi commented on src/propeller/gp.cljc
> +      (prn argmap)
I would avoid printing the entire argmap.

2023-01-06 00:31 UTC, dndang23 reviewed
Hi Ryan, could you review the changes I made based on your comments?

2023-01-07 16:36 UTC, ryanboldi approved these changes
Looks good now. Good work!

2023-01-07 16:46 UTC, merged

2023-01-07 17:01 UTC, lspector commented
Thanks @dndang23 and @ryanboldi for your work on this! I've also patched up the formatting.